// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharee.Application.Data;

#nullable disable

namespace Sharee.Application.Migrations
{
    [DbContext(typeof(ShareeDbContext))]
    [Migration("20230812205452_AddToken")]
    partial class AddToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Sharee.Application.Data.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime?>("LastDownloadTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_download_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_time");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
